### ISSUE TITLE
Feature :: 외출외박

### ISSUE THREAD

**Issue by BaekSeungHa** [Team-B1ND/dodamdodam-teacher-web#4]
![스크린샷 2023-07-28 오후 12 09 57](https://github.com/Team-B1ND/DodamDodam_Teacher_WEB_V2/assets/101560680/36f44f52-5452-4881-bafc-02c7607c7fb4)
![스크린샷 2023-07-28 오후 12 10 16](https://github.com/Team-B1ND/DodamDodam_Teacher_WEB_V2/assets/101560680/35d7f526-c61e-4b01-bff7-532a6f69388c)
![스크린샷 2023-07-28 오후 12 10 24](https://github.com/Team-B1ND/DodamDodam_Teacher_WEB_V2/assets/101560680/1821800c-b225-4b30-97b3-a6c0924d93db)

**Comment by HAERIM0** [comment]
[67f062e](https://github.com/Team-B1ND/dodamdodam-teacher-web/commit/67f062e08f72efe7632803bdb021c4549fa36174)
-> 모르고 이슈 6번으로 push했습니다.. 참고해주세요
