### ISSUE TITLE
Feature :: 결석

### ISSUE THREAD

**Issue by BaekSeungHa** [Team-B1ND/dodamdodam-teacher-web#8]
![스크린샷 2023-07-28 오후 12 15 08](https://github.com/Team-B1ND/DodamDodam_Teacher_WEB_V2/assets/101560680/5d68f102-3af6-43c0-9239-0aa94506638f)

**Comment by Sanghyun0505** [comment]
쓰지 않는 기능이므로 close 하겠습니다.
